### ISSUE TITLE
Including (sub) documents

### ISSUE THREAD

**Issue by vnijs** [lmmx/devnotes#1]
Saw your blog plots. Thanks for putting that together. FYI a convenient way to include (sub) documents in another Rmd file is to use the `child` option (http://stackoverflow.com/a/17605475/1974918)

**Comment by lmmx** [comment]
Ah thank you so much! As I guess you read I was considering running `brew` on an intermediate to write the YAML list of what to `include:` - since the child option seems to take a character vector, I'm sure I could run `list.files()` and supply the list programmatically through that instead... Hmm...

**Comment by vnijs** [comment]
That should work I think. There are really powerful tools to create documents with r and markdown but imho they lack simple examples to help users get started. hadley/rsmith , for example, seems really interesting but it is not very clear how to use whisker tempting with rmarkdown documents. Anyway, keep posting!

**Comment by lmmx** [comment]
Code chunk now in the example file [analysis.Rmd](https://github.com/lmmx/tomasetti-vogelstein-2015/blob/master/documents/analysis.Rmd) rather than the YAML `includes:` header :

<pre>
```{r child = c("analysis-i.md", "analysis-ii.md", "analysis-iii.md")}
# The 'children' of the 'main' document can be specified (with the same result as the `include: after_body:` field in the YAML header) with either an explicit list:
#
# ```{r child = c("analysis-i.md", "analysis-ii.md", "analysis-iii.md")}
# ```
#
# or a call to `list.files`:
#
# ```{r child = list.files(pattern = 'analysis-.*?\\.md')}
# ```
# The former is preferable, but NB throws error if pattern doesn't match since child = character(0)
```
</pre>

Using the explicit list rather than file globbing for now as commented, an if statement would be needed to use `list.files`, and of note the ordering of Roman numerals would not be as expected based on default `list.files` alphanumeric ordering (markdown files would be appended out of order).
